id: 36fd13b247c04608a6f8e91f1ba93239
initial_creation_type: ocr
source_metadata:
  volumes:
    2523b2aab26d41afbcb87362393af254:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
